name: BUILD_MACOS

on:
  push:
    # paths:
    #   - '**.js'
  schedule:
    - cron: '0 0 * * mon'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/crazy-max/osxcross
    steps:
    - name: "checkout repo"
      uses: actions/checkout@v4
    - name: "Build"
      uses: actions/checkout@v4
      run: |
        bash build.sh
    - name: "Upload artifact"
      uses: actions/upload-artifact@v4
      with:
        name: macos-${{ env.version }}
        path: "godot/Godot.tgz"
        retention-days: 3
