name: BUILD_MACOS

on:
  push:
    # paths:
    #   - '**.js'
  schedule:
    - cron: '0 0 * * mon'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "checkout repo"
      uses: actions/checkout@v4
    - name: "Build"
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libarchive-tools scons
        curl -fSL -JO http://mirrors.edge.kernel.org/ubuntu/pool/universe/x/xar/libxar-dev_1.8.0.498-2_amd64.deb
        curl -fSL -JO http://mirrors.edge.kernel.org/ubuntu/pool/universe/x/xar/libxar1_1.8.0.498-2_amd64.deb
        curl -fSL -JO http://mirrors.edge.kernel.org/ubuntu/pool/universe/x/xar/xar_1.8.0.498-2_amd64.deb
        sudo dpkg -i libxar1_1.8.0.498-2_amd64.deb
        sudo dpkg -i xar_1.8.0.498-2_amd64.deb
        sudo dpkg -i libxar-dev_1.8.0.498-2_amd64.deb
        bash build.sh
    - name: "Upload artifact"
      uses: actions/upload-artifact@v4
      with:
        name: macos-${{ env.version }}
        path: "godot/Godot.tgz"
        retention-days: 3
