name: BUILD_MACOS

on:
  push:
    # paths:
    #   - '**.js'
  schedule:
    - cron: '0 0 * * mon'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "checkout repo"
      uses: actions/checkout@v4
    - name: "Build"
      shell: bash
      run: |
        bash build.sh
    - name: "Upload artifact"
      uses: actions/upload-artifact@v4
      with:
        name: macos-build
        path: "Godot.tgz"
        retention-days: 3
