name: BUILD_MACOS

on:
  push:
    # paths:
    #   - '**.js'
  schedule:
    - cron: '0 0 * * mon'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "checkout repo"
      uses: actions/checkout@v4
    - name: "Build"
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libarchive-tools scons
        mkdir -p osxcross
        docker pull ghcr.io/joseluisq/docker-osxcross:1.0.0-beta.2
        docker create --name tmp-osxcross ghcr.io/joseluisq/docker-osxcross:1.0.0-beta.2 sleep infinity
        docker cp tmp-osxcross:/usr/local/osxcross/. ./osxcross/
        docker rm tmp-osxcross
        docker image rm ghcr.io/joseluisq/docker-osxcross:1.0.0-beta.2
        sudo cp ./osxcross/lib/. /usr/lib/x86_64-linux-gnu/
        bash build.sh
    - name: "Upload artifact"
      uses: actions/upload-artifact@v4
      with:
        name: macos-${{ env.version }}
        path: "godot/Godot.tgz"
        retention-days: 3
